### ISSUE TITLE
A General Question

### ISSUE THREAD

**Issue by MehdiRaash** [mxmzb/react-marquee-slider#1]
Hello, firstly I should say 'good job', thanks for this repo, It was a need, really. Danke!

I'm gonna use a crawler in my software(in TV live-stream they call it a crawler), At first I was going to build my own one, so I were quit aware of the configuration, but the time I saw your repo, I had decided to use this repo.

Would you please inform me of **any limitations** or **lack of features** in this repo?

**Comment by mxmzb** [comment]
Thank you for your words, I appreciate a lot!

I don't think I understood what you want to build, do you have an example? So here are a few limitations or lack of features I can think of, but it would be very helpful if you could ask specific questions for what you are looking for (e.g. "Does this plugin have feature XYZ? Can you do that specific thing with this plugin?"):

1. It won't render server-side, so it will be hard to make this SEO-compatible
2. You need to manually find a good combination of the configuration options depending on the number of elements you put in and how large they are, also you need to adjust those for various screen sizes

Other than that, it does what it says. I don't know, what kind of limitations you are expecting or looking for. But if you have something in mind, please ask! Thank you.

**Comment by MehdiRaash** [comment]
Thanks for being available here.
In my company we are building something similar to CG, a custom one( _a CG is a software that a you can define effects and other stuff to put on a broadcaster, as a layer. TV logo, and news marquee and many other objects that a TV program would need_).

For my case now, I'm gonna have a **text marquee**, but with control on when it starts, finishes, and most importantly to change velocity while some text goes off. They are some basic needs of mine.

**Comment by mxmzb** [comment]
Sounds doable, and of course you can also use text to run through the marquee. However, I think you would be better of with a simple CSS solution like this:

https://stackoverflow.com/a/21233577/744230

Which also will work better with search engines. If you need a feature from this repo that the above solution cannot provide, I'd suggest you simply go with it. If there come up issues, you can post here and I'll try to help!
