### ISSUE TITLE
Prop Velocity=0 crashes

### ISSUE THREAD

**Issue by Yiannimoustakas** [mxmzb/react-marquee-slider#2]
Line 90 in `Motion.tsx` `const animationDuration = circumference / velocity;` will crash if velocity is 0.

Our current app requires a feature to pause the carousel on hover. Any chance you could add this in? 

Thanks

**Comment by mxmzb** [comment]
I like the feature idea, will see when and how I can implement it!

**Comment by Yiannimoustakas** [comment]
You might want a more intricate solution but would something like this work for our case?
`const animationDuration = velocity === 0 ? 0 : circumference / velocity;`

**Comment by mxmzb** [comment]
I can't tell right now (writing from phone). 

In the meantime, you are very welcome to fork and try it. If it works to your likings, I think that is a good solution and would be happy to merge a PR!

**Comment by mxmzb** [comment]
Just released 1.1.0, which allows you to set `velocity=0` and thereby stopping the animation!

**Comment by Yiannimoustakas** [comment]
That’s awesome, thanks so much for getting back to me!
