### ISSUE TITLE
Disable on desktop

### ISSUE THREAD

**Issue by zeshhaan** [mxmzb/react-marquee-slider#22]
I was looking at how to disable the slider on desktop. I guess i need to write the logic inside `onFinish`? But i don't want the slider to run/scroll in the desktop at the first place. Is that achievable?

**Comment by mxmzb** [comment]
no, that doesn't have to do anything with the slider. determine in a parent component whether the client is on desktop or not (e.g. look at window size or user agent or or however else you want to define desktop), and simply don't render the slider if you've determined it's desktop.
