### ISSUE TITLE
Enable animation pause

### ISSUE THREAD

**Issue by najaarv** [mxmzb/react-marquee-slider#3]
Hi! first of all, this project looks cool! Awesome work!! Alright, my question is: Is there any prop I can pass on or any CSS way possible so that I can enable animation pause feature when hovering over an item. I tried applying this CSS:
`.glKzCa:hover {
    animation-play-state: paused !important;
}`
This seemed to work until I noticed that if I keep the hover on for too long, elements start overlapping. Also, every child element seems to have random className generated, so one cannot use CSS hover as well properly I guess. It looks like you're splicing up the children of the `Marquee` component into multiple parts in order to have a continuous marquee effect without white space. Can you suggest a workaround or something cause I really want the pause feature?

**Comment by mxmzb** [comment]
Hi @najaarv, thanks, glad you like it!

This is the same issue as https://github.com/mxmzb/react-marquee-slider/issues/2. I'll set apart some time to introduce this feature request ASAP. If you don't want to wait for it, you can look to make it work by making `velocity={0}` work as a prop (it will break [here](https://github.com/mxmzb/react-marquee-slider/blob/master/src/Motion.tsx#L90), and maybe at other places).

**Comment by najaarv** [comment]
Hi, thanks! I'd also like to know if there's any way to display a tooltip/ popover positioned around the hovered/ clicked marquee element. Please let me know if you have any idea how to do that. Thanks.

**Comment by mxmzb** [comment]
Just released 1.1.0, which allows you to set `velocity=0` and thereby stopping the animation!
